apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: jobsvilla-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobsvilla-db
  namespace: jobsvilla-prod
  labels:
    app: jobsvilla-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobsvilla-db
  template:
    metadata:
      labels:
        app: jobsvilla-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: "jobsvilla"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "secret_master_password"
          ports:
            - containerPort: 5432
              name: dbport
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          healthCheck:
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - jobsvilla
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - jobsvilla
            initialDelaySeconds: 15
            periodSeconds: 15
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
